### ISSUE TITLE
Google's Fledge Shim/Microsoft's Parakeet

### ISSUE THREAD

**Issue by brodrigu** [MagniteEngineering/fledge.polyfill#43]
Just stumbled upon a similar project Google is working on: https://github.com/google/fledge-shim. I filed [an issue](https://github.com/google/fledge-shim/issues/7) there to see if we can work together instead of creating competing libraries.

**Comment by iamnewton** [comment]
Registered support for both https://github.com/google/fledge-shim/issues/7#issuecomment-822914155 and https://github.com/WICG/privacy-preserving-ads/issues/14#issuecomment-824195522
