### ISSUE TITLE
Ensure polyfill won't throw errors on non-Fledge based browsers

### ISSUE THREAD

**Issue by brodrigu** [MagniteEngineering/fledge.polyfill#63]
Publishers will need to safely use the polyfill on pages that see traffic from every browser, including those like Safari, Firefox, Brave, etc., that will not be participating in the Fledge trials or the Turtledove-style auctions/interest group tagging.

Create an example that can be loaded on any browser which doesn't throw any errors.

**Comment by iamnewton** [comment]
> Browsers that support the `module` value for the type attribute ignore any script with a `nomodule` attribute. That enables you to use module scripts while also providing nomodule-marked fallback scripts for non-supporting browsers.

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#module_fallback

```html
<script type="module" src="main.js"></script>
<script nomodule src="fallback.js"></script>
```

**Comment by iamnewton** [comment]
```

<script type="module" src="main.js"></script>
<script nomodule>console.log("fledge is not supported on this browser")</script>

```
